version: '3'
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: cs50-final-project
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - ENV=local-docker
